portfolio:
    path:     /
    defaults: { _controller: "PortfolioLaureBundle:Portfolio:index" }

portfolio_new:
    path:     /new
    defaults: { _controller: "PortfolioLaureBundle:Portfolio:new" }

portfolio_create:
    path:     /create
    defaults: { _controller: "PortfolioLaureBundle:Portfolio:create" }
    requirements: { _method: post }

portfolio_edit:
    path:     /{id}/edit
    defaults: { _controller: "PortfolioLaureBundle:Portfolio:edit" }

portfolio_update:
    path:     /{id}/update
    defaults: { _controller: "PortfolioLaureBundle:Portfolio:update" }
    requirements: { _method: post|put }

portfolio_delete:
    path:     /{id}/delete
    defaults: { _controller: "PortfolioLaureBundle:Portfolio:delete" }
    requirements: { _method: post|delete }

PortfolioLaureBundle_image:
    resource: "@PortfolioLaureBundle/Resources/config/routing/image.yml"
    prefix:   /image
